SidBy.Sklad.Web/Controllers/SaleController.cs
using log4net;
using SidBy.Sklad.DataAccess;
using SidBy.Sklad.Domain;
using SidBy.Sklad.Domain.Enums;
using SidBy.Sklad.Web.BL;
using SidBy.Sklad.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trirand.Web.Mvc;

namespace SidBy.Sklad.Web.Controllers
{
    [System.Web.Mvc.Authorize(Roles = "admin,employee")]
    public class SaleController : Controller
    {
        private readonly ILog logger;

        public SaleController()
        {
            logger = LogManager.GetLogger(GetType());
        }

        #region CustomerOrders

        public ActionResult CustomerOrders()
        {
            ViewBag.Title = "Заказы покупателя";
            // Get the model (setup) of the grid defined in the /Models folder.
            var gridModel = new SkladJqGridModel();
            var grid = gridModel.DocumentGrid;

            //// NOTE: you need to call this method in the action that fetches the data as well,
            //// so that the models match
            CustomerOrdersSetupGrid(grid);
            /*
            public int? ContractId { get; set; }
            public int? EmployeeId { get; set; } 
             */

            // Pass the custmomized grid model to the View
            return View(gridModel);
        }

        // This method is called when the grid requests data
        public JsonResult CustomerOrdersSearchGridDataRequested()
        {
            //// Get both the grid Model and the data Model
            var gridModel = new SkladJqGridModel();
            var datacontextModel = new SkladDataContext();
            // customize the default grid model with our custom settings
            CustomerOrdersSetupGrid(gridModel.DocumentGrid);
            return GetDocumentList(gridModel, datacontextModel, EntityEnum.DocumentTypeEnum.CustomerOrders);
        }

        private JsonResult GetDocumentList(SkladJqGridModel gridModel, 
            SkladDataContext datacontextModel, EntityEnum.DocumentTypeEnum docType)
        {
            string contractorIdStr = Request.QueryString["ContractorId"];
            if (!String.IsNullOrEmpty(contractorIdStr))
            {
                var contractor = datacontextModel.Contractors.Where(x =>
                    x.Code.ToLower() == contractorIdStr.ToLower()).FirstOrDefault();
                if (contractor != null)
                {
                    // ContractorName
                    return gridModel.DocumentGrid.DataBind(datacontextModel
                        .Documents.Include("Contractor").Where(x => x.ContractorId == contractor.ContractorId && 
                           x.DocumentTypeId == (int)docType));
                }
            }

            return gridModel.DocumentGrid.DataBind(datacontextModel.Documents.Include("Contractor").Where(x =>
                x.DocumentTypeId == (int)docType));
        }

        private void CustomerOrdersSetupGrid(JQGrid grid)
        {
            SetUpGrid(grid, "CustomerOrdersGrid1",
                Url.Action("CustomerOrdersSearchGridDataRequested"),
                Url.Action("DocumentItemEditRows", "Home"));

            SetUpContractorEmployeeEditDropDown(grid);
            // +планируемая дата отгрузки
        }

        #endregion

        #region Shipment

        public ActionResult Shipment()
        {
            ViewBag.Title = "Отгрузки";
            // Get the model (setup) of the grid defined in the /Models folder.
            var gridModel = new SkladJqGridModel();
            var grid = gridModel.DocumentGrid;

            //// NOTE: you need to call this method in the action that fetches the data as well,
            //// so that the models match
            ShipmentSetupGrid(grid);

            // Pass the custmomized grid model to the View
            return View(gridModel);
        }

        // This method is called when the grid requests data
        public JsonResult ShipmentSearchGridDataRequested()
        {
            // Get both the grid Model and the data Model
            // The data model in our case is an autogenerated linq2sql database based on Northwind.
            var gridModel = new SkladJqGridModel();
            var datacontextModel = new SkladDataContext();
            // customize the default grid model with our custom settings
            ShipmentSetupGrid(gridModel.DocumentGrid);

            return GetDocumentList(gridModel, datacontextModel, EntityEnum.DocumentTypeEnum.Shipment);
        }

        private void ShipmentSetupGrid(JQGrid grid)
        {
            SetUpGrid(grid, "ShipmentGrid1",
                Url.Action("ShipmentSearchGridDataRequested"),
                Url.Action("DocumentItemEditRows", "Home"));
            SetUpContractorEmployeeEditDropDown(grid);
        }

        #endregion

        #region Refunds

        public ActionResult Refunds()
        {
            ViewBag.Title = "Возвраты покупателя";
            // Get the model (setup) of the grid defined in the /Models folder.
            var gridModel = new SkladJqGridModel();
            var grid = gridModel.DocumentGrid;

            //// NOTE: you need to call this method in the action that fetches the data as well,
            //// so that the models match
            RefundsSetupGrid(grid);

            // Создать grid со списком товаров с возвратом за определённый день
            // Можно сделать просто полный список всех товаров из проведённых
            // документов возвратов
            var gridProducts = gridModel.ProductLineGrid;
            RefundsProductSetupGrid(gridProducts);
            ViewBag.GridProducts = gridProducts;

            // Pass the custmomized grid model to the View
            return View(gridModel);
        }

        private void RefundsProductSetupGrid(JQGrid grid)
        {
            SetUpGrid(grid, "RefundsProductGrid1",
                Url.Action("RefundsProductSearchGridDataRequested"),
                Url.Action("DocumentEditRows", "Home"));

            grid.ToolBarSettings.ShowAddButton = false;
    
            SetUpRefundsProductLineColumns(grid);
            SetUpRefundsProductLineGroupingGrandTotal(grid);
        }

        private List<ProductLine> FilterProductLinesByManager(SkladDataContext context, int managerId, List<ProductLine> prods)
        {
            var filteredProducts = new List<ProductLine>();
            foreach (var product in prods)
            { 
                var factory = context.Contractors.Where(x => x.Code.ToLower() == product.SupplierCode.ToLower()).FirstOrDefault();
                // failed to find factory. In this case - dont miss product
                if (factory == null)
                    filteredProducts.Add(product);
                else if(factory.ResponsibleId == managerId)
                    filteredProducts.Add(product);
            }

            return filteredProducts;
        }

        private IQueryable<ProductLine> GetRefundsProductLines(SkladDataContext context, DateTime day, int? contractorId, int? managerId)
        {
            List<Document> docs = null;
            if (contractorId.HasValue && contractorId.Value > 0)
            {
                docs = context.Documents
                .Where(x => x.CreatedOf == day && x.IsCommitted == true && x.DocumentTypeId == (int)EntityEnum.DocumentTypeEnum.Refunds
                && x.ContractorId == contractorId.Value).ToList();
            }
            else {
                docs = context.Documents
                  .Where(x => x.CreatedOf == day && x.IsCommitted == true && x.DocumentTypeId == (int)EntityEnum.DocumentTypeEnum.Refunds).ToList();
            }
            if (docs != null)
            {
                if (docs.Count > 0)
                {
                    var docIds = docs.Select(x => x.DocumentId).ToArray();
                    var products = context.ProductLines.Where(x => docIds.Contains(x.DocumentId));

                    if (managerId.HasValue && managerId.Value > 0)
                        products = FilterProductLinesByManager(context, managerId.Value, products.ToList()).AsQueryable();
                    if (contractorId.HasValue && contractorId.Value > 0)
                        return products;
                    else
                    {
                        // в комментариях указать клиента
                        foreach (var product in products)
                        {
                            var docsP = context.Documents.Where(x => x.DocumentId == product.DocumentId).FirstOrDefault();
                            if (docsP != null) {
                                product.Comment = "Возврат от: " + docsP.Contractor.Code + ". " + product.Comment;
                            }
                        }

                        return products.AsQueryable();
                    }
                }
            }

            return new List<ProductLine>().AsQueryable();
        }

        public JsonResult RefundsProductSearchGridDataRequested(DateTime? refundsReportDate)
        {
            if (!refundsReportDate.HasValue)
                refundsReportDate = DateTime.Now;
        
            // Get both the grid Model and the data Model
            // The data model in our case is an autogenerated linq2sql database based on Northwind.
            var gridModel = new SkladJqGridModel();
            var datacontextModel = new SkladDataContext();
            SetUpRefundsProductLineColumns(gridModel.ProductLineGrid);
            SetUpRefundsProductLineGroupingGrandTotal(gridModel.ProductLineGrid);
            // customize the default grid model with our custom settings
            //JQGridState gridState = gridModel.ProductLineGrid.GetState();

            // Need this to enable ExportToExcelRefundsByDay
            // Session["refundsProductLinesGridState"] = gridState;
            int contractorId = 0;
            if (Request.Params["contractorId"] != null)

SidBy.Sklad.Web/Controllers/WarehouseController.cs
using log4net;
using SidBy.Sklad.DataAccess;
using SidBy.Sklad.Domain;
using SidBy.Sklad.Domain.Enums;
using SidBy.Sklad.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trirand.Web.Mvc;

namespace SidBy.Sklad.Web.Controllers
{
    [System.Web.Mvc.Authorize(Roles = "admin,employee")]
    public class WarehouseController : Controller
    {
        private readonly ILog logger;

        public WarehouseController()
        {
            logger = LogManager.GetLogger(GetType());
        }

        #region Posting

        public ActionResult Posting()
        {
            ViewBag.Title = "Оприходования";
            // Get the model (setup) of the grid defined in the /Models folder.
            var gridModel = new SkladJqGridModel();
            var grid = gridModel.DocumentGrid;

            //// NOTE: you need to call this method in the action that fetches the data as well,
            //// so that the models match
            PostingSetupGrid(grid);

            // Pass the custmomized grid model to the View
            return View(gridModel);
        }

        // This method is called when the grid requests data
        public JsonResult PostingSearchGridDataRequested()
        {
            // Get both the grid Model and the data Model
            // The data model in our case is an autogenerated linq2sql database based on Northwind.
            var gridModel = new SkladJqGridModel();
            var datacontextModel = new SkladDataContext();
            // customize the default grid model with our custom settings
            PostingSetupGrid(gridModel.DocumentGrid);

            return gridModel.DocumentGrid.DataBind(datacontextModel.Documents.Where(x =>
                x.DocumentTypeId == (int)EntityEnum.DocumentTypeEnum.Posting));
        }

        private void PostingSetupGrid(JQGrid grid)
        {
            SetUpGrid(grid, "PostingGrid1",
                Url.Action("PostingSearchGridDataRequested"),
                Url.Action("DocumentItemEditRows", "Home"));
        }

        #endregion

        #region Cancellation

        public ActionResult Cancellation()
        {
            ViewBag.Title = "Списания";
            // Get the model (setup) of the grid defined in the /Models folder.
            var gridModel = new SkladJqGridModel();
            var grid = gridModel.DocumentGrid;

            //// NOTE: you need to call this method in the action that fetches the data as well,
            //// so that the models match
            CancellationSetupGrid(grid);

            // Pass the custmomized grid model to the View
            return View(gridModel);
        }

        // This method is called when the grid requests data
        public JsonResult CancellationSearchGridDataRequested()
        {
            // Get both the grid Model and the data Model
            // The data model in our case is an autogenerated linq2sql database based on Northwind.
            var gridModel = new SkladJqGridModel();
            var datacontextModel = new SkladDataContext();
            // customize the default grid model with our custom settings
            CancellationSetupGrid(gridModel.DocumentGrid);

            return gridModel.DocumentGrid.DataBind(datacontextModel.Documents.Where(x =>
                x.DocumentTypeId == (int)EntityEnum.DocumentTypeEnum.Cancellation));
        }

        private void CancellationSetupGrid(JQGrid grid)
        {
            SetUpGrid(grid, "CancellationGrid1",
                Url.Action("CancellationSearchGridDataRequested"),
                Url.Action("DocumentItemEditRows", "Home"));

        }

        #endregion

        private void SetUpGrid(JQGrid grid, string gridID, string dataUrl, string editUrl)
        {
            // Customize/change some of the default settings for this model
            // ID is a mandatory field. Must by unique if you have several grids on one page.
            grid.ID = gridID;

            // Setting the DataUrl to an action (method) in the controller is required.
            // This action will return the data needed by the grid
            grid.DataUrl = dataUrl;
            grid.EditUrl = editUrl;
            // show the search toolbar
            grid.ToolBarSettings.ShowSearchToolBar = true;
            grid.ToolBarSettings.ShowDeleteButton = true;
            grid.EditDialogSettings.CloseAfterEditing = true;
            grid.ToolBarSettings.ShowAddButton = false;
            grid.AddDialogSettings.CloseAfterAdding = true;
        }
    }
}

SidBy.Sklad.Web/Views/Shared/_JqGridDocumentPartial.cshtml
@model SidBy.Sklad.Web.Models.JqGridViewDocParamsModel
@using Trirand.Web.Mvc
@using SidBy.Sklad.Domain.Enums

@{if(@Model.DocumentTypeId != (int)EntityEnum.DocumentTypeEnum.Refunds){
<script type="text/javascript">

    $(function () {
        $("#@(Model.GridId + "_" + "btnDocumentAdd")").button({
            icons: {
                primary: "ui-icon-plus"
            }
        }).on("click", function (event) {
            window.location.href = "@Url.Action("Document", "Home", new { documentTypeId = Model.DocumentTypeId })";
        });
    });

</script>
}}
<table class="sklad-top-menu">
    <tr>
        <td><div class="sklad-title">@Model.Title</div></td>
        @{if(@Model.DocumentTypeId != (int)EntityEnum.DocumentTypeEnum.Refunds){
        <td><button id="@(Model.GridId + "_" + "btnDocumentAdd")">Создать</button></td>
        }}
        <td>
@Html.Partial("_SearchProductPartial",Model.DocumentTypeId)
        </td>
        @*<td><a href="@Url.Action("Document", "Home", new { documentTypeId = Model.DocumentTypeId })">Создать</a></td>*@
    </tr>
</table>

@Html.Trirand().JQGrid(Model.Grid, Model.GridId)

@Html.Trirand().JQAutoComplete(new JQAutoComplete {
     AutoCompleteMode = AutoCompleteMode.BeginsWith,
        DataUrl = Url.Action("GetContractorByCodeAutoComplete", "Home"),
        DataField = "Code",
        ID = "ContractorId",
        DisplayMode = AutoCompleteDisplayMode.ControlEditor,
        MinLength = 2,
}, "ContractorAutoComplete")


    @Html.Trirand().JQDatePicker(new JQDatePicker {
    MaxDate = DateTime.MaxValue,
    MinDate = new DateTime(2013,1,1),
    DisplayMode = DatePickerDisplayMode.ControlEditor,
    ShowOn = ShowOn.Focus,
    OnSelectedCallbackFunction = "CreatedOfPickerDateSelectedTrigger",
}, "CreatedOfPicker")

    @Html.Trirand().JQDatePicker(new JQDatePicker {
    MaxDate = DateTime.MaxValue,
    MinDate = new DateTime(2013,1,1),
    DisplayMode = DatePickerDisplayMode.ControlEditor,
    ShowOn = ShowOn.Focus,
    OnSelectedCallbackFunction = "CreatedOfPickerDateSelectedTrigger",
}, "PlannedDatePicker")

    <script type="text/javascript">
        function CreatedOfPickerDateSelectedTrigger(dateText, inst) {
            var sgrid = $("#@Model.GridId")[0];
            sgrid.triggerToolbar();
        }

    function formatDocumentEditLink(cellvalue, options, rowObject) {
        return '<ul class="grid-ui-icons"><li><a href="/Home/Document?documentId='
            + cellvalue + '" title="Редактировать"><span class="ui-icon ui-icon-pencil"></span></a></li></ul>';
    }
    function unFormatDocumentEditLink(cellvalue, options, cell) {
        return $('img', cell).attr('src');
    }

    function customSummaryFunc(val, name, record) {
        // console.log(val);
        return parseFloat(val || 0) + parseFloat((record[name] || 0));
    }


</script>

SidBy.Sklad.Web/Views/Shared/_JqGridStandart.cshtml
@model SidBy.Sklad.Web.Models.JqGridViewParamsModel
@using Trirand.Web.Mvc

<script type="text/javascript">
    $(function () {
        $("#@(Model.GridId + "_" + "btnContractorAdd")").button({
            icons: {
                primary: "ui-icon-plus"
            }
        }).on("click", function (event) {
            $("#@Model.GridId").jqGrid('editGridRow', "new", {
                rowID: "new_row",
                initdata: {},
                position: "first",
                useDefValues: false,
                useFormatter: false,
                addRowParams: { extraparam: {} },
                width: 450
            });
        });
    });
</script>

<table class="sklad-top-menu">
    <tr>
        <td><div class="sklad-title">@Model.Title</div></td>
        <td><button id="@(Model.GridId + "_" + "btnContractorAdd")">Создать</button></td>
    </tr>
</table>

@Html.Trirand().JQGrid(Model.Grid, Model.GridId)

SidBy.Sklad.Web/Views/Shared/_Layout.cshtml
@using SidBy.Sklad.Web.Resources.Views.Shared

<!DOCTYPE html>
<html lang="@_LayoutStrings.Lang">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - @_LayoutStrings.ApplicationName</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes/redmond/css")
        @Styles.Render("~/Content/themes/jqgrid/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/fileupload")

    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink(_LayoutStrings.Logo, "Index", "Indicators")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                </div>
                <div class="clear-both"></div>
                @if (User.IsInRole("employee") || User.IsInRole("admin"))
                {
                <div id="sklad-nav-outer">
                    <nav id="sklad-nav-tabs" class="no-border">
                        <ul>
                        <li><a href="#sklad-nav-tabs-1">Моя компания</a></li>
                       @* <li><a href="#sklad-nav-tabs-2">Закупки</a></li>*@
                        <li><a href="#sklad-nav-tabs-3">Продажи</a></li>
                        <li><a href="#sklad-nav-tabs-4">Склад</a></li>
                        <li><a href="#sklad-nav-tabs-5">Справочники</a></li>
                        </ul>
                        <div id="sklad-nav-tabs-1">
                            <ul class="sklad-nav-links">
                                <li>@Html.ActionLink("Показатели", "Index", "Indicators")</li>
                                @*<li>@Html.ActionLink("Юр. лица", "LegalEntity", "MyCompany")</li>*@
                                <li>@Html.ActionLink("Контакты", "MyEmployees", "MyCompany")</li>
                              @*  <li>@Html.ActionLink("Склады", "Warehouse", "MyCompany")</li>*@
                                <li><a href="#">Документы</a></li>
                                <li>@Html.ActionLink("Администрирование", "Index", "Administration")</li>
                            </ul>
                        </div>
                       @* <div id="sklad-nav-tabs-2">
                            <ul class="sklad-nav-links">
                                <li><a href="#">Заказы поставщикам</a></li>
                                <li><a href="#">Приёмки</a></li>
                                <li><a href="#">Возвраты поставщикам</a></li>
                            </ul>
                        </div>*@
                        <div id="sklad-nav-tabs-3">
                            <ul class="sklad-nav-links">
                                <li>@Html.ActionLink("Заказы покупателей", "CustomerOrders", "Sale")</li>
                                <li>@Html.ActionLink("Отгрузки", "Shipment", "Sale")</li>
                                <li>@Html.ActionLink("Возвраты покупателей", "Refunds", "Sale")</li>
                                <li><a href="#"><i>Прибыльность</i></a></li>
                                <li><a href="#"><i>Задолженность</i></a></li>
                            </ul>
                        </div>
                        <div id="sklad-nav-tabs-4">
                            <ul class="sklad-nav-links">
                                <li>@Html.ActionLink("Списания", "Cancellation", "Warehouse")</li>
                                <li>@Html.ActionLink("Оприходования", "Posting", "Warehouse")</li>
                                <li><a href="#"><i>Остатки</i></a></li>
                                <li><a href="#"><i>Обороты</i></a></li>
                            </ul>
                        </div>
                        <div id="sklad-nav-tabs-5">
                            <ul class="sklad-nav-links">
                                <li>@Html.ActionLink("Товары", "Product", "Reference")</li>
                                @*<li><a href="#">Серии</a></li>*@
                                <li>@Html.ActionLink("Контрагенты", "Contractor", "Reference")</li>
                                @*<li>@Html.ActionLink("Регион", "Region", "Reference")</li>*@
                                @*<li><a href="#">Валюты</a></li>*@
                                <li><a href="#">Договоры</a></li>
                            </ul>
                        </div>
                    </nav>
                 </div>
                }

                @*    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink(_LayoutStrings.Home, "Index", "Home")</li>
                            <li>@Html.ActionLink(_LayoutStrings.About, "About", "Home")</li>
                            <li>@Html.ActionLink(_LayoutStrings.Contact, "Contact", "Home")</li>
                        </ul>
                    </nav>*@
              
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - @_LayoutStrings.ApplicationName</p>
                </div>
            </div>
        </footer>

    
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/jqgrid")
   
        @Scripts.Render("~/bundles/skladui")
        @RenderSection("scripts", required: false)
    </body>
</html>

SidBy.Sklad.Web/Views/Shared/_Log.cshtml
@model SidBy.Sklad.Web.Models.LogJqGridModel
@using Trirand.Web.Mvc

<h3>Лог событий</h3>
@Html.Trirand().JQGrid(Model.LogGrid, "Log1")

@Html.Trirand().JQDatePicker(new JQDatePicker { 
    MaxDate = DateTime.Now,
    MinDate = new DateTime(2014,1,1),
    DisplayMode = DatePickerDisplayMode.ControlEditor,
    ShowOn = ShowOn.Focus,
    OnSelectedCallbackFunction = "LogCreatedPickerDateSelectedTrigger",
}, "LogCreatedPicker")

<script type="text/javascript">
    function LogCreatedPickerDateSelectedTrigger(dateText, inst)
    {
        var sgrid = $("#Log1")[0];
        sgrid.triggerToolbar();
    }

    //function OrderByDateCreated(data)
    //{
    //    //if (data.nodeType) {
    //        setTimeout(function () {
    //            var sgrid = $("#Log1");
    //            sgrid.sortGrid('Date');
    //            sgrid.trigger("reloadGrid");
    //        }, 10000);
    //    //}
    //    console.log(data);
    //}
</script>

SidBy.Sklad.Web/Views/Shared/_SearchProductPartial.cshtml
@model int
<p>
    <span class="SupplierName">Код фабрики</span>
     <input type="text" id="ContractorCode" style="width:120px;" name="ContractorCode" />
<input type="hidden" id="SupplierId" name="SupplierId" />
<span class="article">Артикул
<input type="text" id="Article" style="width:120px;" name="Article" /></span>
 <span id="searchProductUrls"></span>
</p>



<script>
    $(document).ready(function () {
        $("#Article").autocomplete({
            source: function (request, response) {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("GetProductByArticle", "Home")",
                    data: {
                        term: request.term,
                        supplierId: $("#SupplierId").val(),
                        count: 20
                    },
                    contentType: "application/json;charset=utf-8",
                    dataType: "json",
                    processdata: true,
                    async: true,
                    cache: false,
                    success: function (data) {
                        response(data);
                    },
                })
            },
            minLength: 2,
            select: function (event, ui) {
                // get related documents of this
                // product by supplierId and ui.item.Article
                $('#Article').val(ui.item.Article);
                if (ui.item.ProductId)
                {
                    $.ajax({
                        type: "GET",
                        url: "@Url.Action("GetDocumentsByProduct", "Home", new { documentTypeId = Model })",
                        data: {
                            productId: ui.item.ProductId,
                         
                            count: 100
                        },
                        contentType: "application/json;charset=utf-8",
                        dataType: "json",
                        processdata: true,
                        async: true,
                        cache: false,
                        success: function (data) {
                            $('#searchProductUrls').html('');
                            if (data) {
                                if (data.length > 0) {
                                    $.each(data, function (index, value) {
                                        var docDate = new Date(parseInt(value.CreatedOf.substr(6)));
                                        $('#searchProductUrls')
                                            .append('<a class="' + (value.IsCommitted ? "commited" : "not-commited") +
                                            '" target="_blank" href="@Url.Content("~/Home/Document")?documentId=' +
                                            value.DocumentId + '">' +
                                            getDocumentTypeTitle(value.DocumentTypeId) + ' №' + value.Number + ' от ' +
                                            //("0" + this.getDate()).slice(-2)
                                            +("0" + docDate.getDate()).slice(-2) + '.' 
                                            + ("0" + (docDate.getMonth() + 1)).slice(-2) + '.' + docDate.getFullYear() + '</a> ');

                                        /*
                                        u.DocumentId, 
                              u.Document.IsCommitted, u.Document.Number,
                              u.Document.DocumentTypeId,
                              u.Document.CreatedOf,
                                        */
                                    });
                                }
                                else {
                                    $('#searchProductUrls').html('Данный товар не найден ни в одном документе');
                                }
                            }
                            else {
                                $('#searchProductUrls').html('Уточните поиск. Товар не найден!');
                            }

                           // console.log(data);
                        },
                    })
                }

                return false;
            }
        }).data("ui-autocomplete")._renderItem = function (ul, item) {
            return $("<li>")
            .append("<a>" + item.Article + "</a>")
            .appendTo(ul);
            //"<br>" + item.Name + item.SurName + 
        };

        $("#ContractorCode").autocomplete({
            source: function (request, response) {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("GetSupplierByCode", "Reference")",
                    data: { term: request.term, count: 20 },
                    contentType: "application/json;charset=utf-8",
                    dataType: "json",
                    processdata: true,
                    async: true,
                    cache: false,
                    success: function (data) {
                        response(data);
                    },
                })
            },
            minLength: 2,
            select: function (event, ui) {
                var text = "Товар от фабрики: ";
                $(".SupplierName").text(text + ui.item.Name + " (" + ui.item.Code + ")");
                $("#SupplierId").val(ui.item.ContractorId);
                $("#ContractorCode").val(ui.item.Code);
                $("#ProductFields").css('visibility', 'visible').hide().fadeIn('slow');;
                return false;
            }
        }).data("ui-autocomplete")._renderItem = function (ul, item) {
            return $("<li>")
            .append("<a>" + item.Code + "</a>")
            .appendTo(ul);
        };
    });
 </script>