SidBy.Sklad.Web/Controllers/ReferenceController.cs
using log4net;
using SidBy.Common.Helpers;
using SidBy.Sklad.DataAccess;
using SidBy.Sklad.Domain;
using SidBy.Sklad.Web.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trirand.Web.Mvc;
using SidBy.Sklad.Domain.Enums;

namespace SidBy.Sklad.Web.Controllers
{
    [System.Web.Mvc.Authorize(Roles = "admin,employee")]
    public class ReferenceController : Controller
    {
        private readonly ILog logger;

        public ReferenceController()
        {
            logger = LogManager.GetLogger(GetType());
        }

        //#region Region
        //public ActionResult Region()
        //{
        //    ViewBag.Title = "Регион";
        //    // Get the model (setup) of the grid defined in the /Models folder.
        //    var gridModel = new SkladJqGridModel();
        //    var grid = gridModel.RegionGrid;

        //    // NOTE: you need to call this method in the action that fetches the data as well,
        //    // so that the models match
        //    RegionSetupGrid(grid);

        //    // Pass the custmomized grid model to the View
        //    return View(gridModel);
        //}

        //// This method is called when the grid requests data
        //public JsonResult RegionSearchGridDataRequested()
        //{
        //    // Get both the grid Model and the data Model
        //    // The data model in our case is an autogenerated linq2sql database based on Northwind.
        //    var gridModel = new SkladJqGridModel();
        //    var datacontextModel = new SkladDataContext();
        //    // customize the default grid model with our custom settings
        //    RegionSetupGrid(gridModel.RegionGrid);

        //    // return the result of the DataBind method, passing the datasource as a parameter
        //    // jqGrid for ASP.NET MVC automatically takes care of paging, sorting, filtering/searching, etc
        //    return gridModel.RegionGrid.DataBind(datacontextModel.Regions);
        //}

        //private void RegionSetupGrid(JQGrid grid)
        //{
        //    SetUpGrid(grid, "RegionGrid1",
        //        Url.Action("RegionSearchGridDataRequested"),
        //        Url.Action("RegionEditRows"));
        //}

        //public ActionResult RegionEditRows(Region editedItem)
        //{
        //    // Get the grid and database models
        //    var gridModel = new SkladJqGridModel();
        //    var datacontextModel = new SkladDataContext();

        //    // If we are in "Edit" mode
        //    if (gridModel.RegionGrid.AjaxCallBackMode == AjaxCallBackMode.EditRow)
        //    {
        //        // Get the data from and find the item corresponding to the edited row
        //        Region item = (from x in datacontextModel.Regions
        //                          where x.RegionId == editedItem.RegionId
        //                          select x).First<Region>();

        //        // update the item information
        //        UpdateRegion(item, editedItem);

        //        datacontextModel.SaveChanges();
        //    }

        //    if (gridModel.RegionGrid.AjaxCallBackMode == AjaxCallBackMode.AddRow)
        //    {
        //        // since we are adding a new item, create a new istance
        //        Region item = new Region();
        //        // set the new item information
        //        UpdateRegion(item, editedItem);

        //        datacontextModel.Regions.Add(item);
        //        datacontextModel.SaveChanges();
        //    }
        //    if (gridModel.RegionGrid.AjaxCallBackMode == AjaxCallBackMode.DeleteRow)
        //    {
        //        Region item = (from x in datacontextModel.Regions
        //                          where x.RegionId == editedItem.RegionId
        //                          select x)
        //                       .First<Region>();

        //        // delete the record                
        //        datacontextModel.Regions.Remove(item);
        //        datacontextModel.SaveChanges();
        //    }

        //    return RedirectToAction("Region", "Reference");
        //}

        //private void UpdateRegion(Region item, Region editedItem)
        //{
        //    item.Name = editedItem.Name;
        //}

        //#endregion

        #region Contractor
        public ActionResult Contractor()
        {
            ViewBag.Title = "Контрагент";
            // Get the model (setup) of the grid defined in the /Models folder.
            var gridModel = new SkladJqGridModel();
            var grid = gridModel.ContractorGrid;

            // NOTE: you need to call this method in the action that fetches the data as well,
            // so that the models match
            ContractorSetupGrid(grid);

            // Pass the custmomized grid model to the View
            return View(gridModel);
        }

        // This method is called when the grid requests data
        public JsonResult ContractorSearchGridDataRequested()
        {
            // Get both the grid Model and the data Model
            // The data model in our case is an autogenerated linq2sql database based on Northwind.
            var gridModel = new SkladJqGridModel();
            var datacontextModel = new SkladDataContext();
            // customize the default grid model with our custom settings
            ContractorSetupGrid(gridModel.ContractorGrid);

            // return the result of the DataBind method, passing the datasource as a parameter
            // jqGrid for ASP.NET MVC automatically takes care of paging, sorting, filtering/searching, etc
            return gridModel.ContractorGrid.DataBind(datacontextModel.Contractors);
        }

        private void ContractorSetupGrid(JQGrid grid)
        {
            SetUpGrid(grid, "ContractorGrid1",
                Url.Action("ContractorSearchGridDataRequested"),
                Url.Action("ContractorEditRows"));

            SetUpContractorEditDropDown(grid);
        }

        private void PrepareContractorData(Contractor contractor)
        {
            contractor.Name = (contractor.Name ?? String.Empty).Trim();
            contractor.Code = (contractor.Code ?? String.Empty).Trim();
            contractor.Phone = (contractor.Phone ?? String.Empty).Trim();
            contractor.Fax = (contractor.Fax ?? String.Empty).Trim();
            contractor.Email = (contractor.Email ?? String.Empty).Trim();
            contractor.ActualAddress = (contractor.ActualAddress ?? String.Empty).Trim();
            contractor.Comment = (contractor.Comment ?? String.Empty).Trim();
            contractor.ContactPersonName = (contractor.ContactPersonName ?? String.Empty).Trim();
         
            if (String.IsNullOrEmpty(contractor.Name))
                contractor.Name = contractor.Code;

            if (String.IsNullOrEmpty(contractor.Code))
                contractor.Code = contractor.Name;
        }

        private string ValidateContractorData(DbSet<Contractor> dbSet, Contractor contractor, bool isNew)
        {
            if (String.IsNullOrEmpty(contractor.Name))
                return "Имя пользователя обязательно";

            if (String.IsNullOrEmpty(contractor.Code))
                return "Отображаемое имя обязательно";

            if (isNew)
            {
                Contractor item = dbSet.Where(x =>
                    String.Compare(x.Code, contractor.Code, StringComparison.OrdinalIgnoreCase) == 0
                    || x.Name == contractor.Name).FirstOrDefault<Contractor>();

                if (item != null)
                    return "Контрагент с таким именем существует";
            }
            else
            {
                Contractor item = (from x in dbSet
                                   where x.ContractorId == contractor.ContractorId
                                   select x).First<Contractor>();

                // if DisplayName was changed
                if (item.Name.ToLower() != contractor.Name.ToLower())
                {
                    if ((from x in dbSet
                         where String.Compare(x.Name, contractor.Name, StringComparison.OrdinalIgnoreCase) == 0
                         select x).FirstOrDefault<Contractor>() != null)
                        return "Контрагент с таким именем существует";
                }

                // if UserName was changed
                if (item.Code.ToLower() != contractor.Code.ToLower())
                {
                    if ((from x in dbSet
                         where String.Compare(x.Code, contractor.Code, StringComparison.OrdinalIgnoreCase) == 0
                         select x).FirstOrDefault<Contractor>() != null)
                        return "Контрагент с таким именем существует";
                }
            }

            if (!String.IsNullOrEmpty(contractor.Email))
            {
                if (!ValidationHelper.IsValidEmail(contractor.Email))
                    return "Неверный формат email";
            }

            return String.Empty;
        }

        public ActionResult ContractorEditRows(Contractor editedItem)
        {
            // Get the grid and database models
            var gridModel = new SkladJqGridModel();
            var datacontextModel = new SkladDataContext();

            // If we are in "Edit" mode
            if (gridModel.ContractorGrid.AjaxCallBackMode == AjaxCallBackMode.EditRow)
            {
                PrepareContractorData(editedItem);

                string validationMessage = ValidateContractorData(datacontextModel.Contractors, editedItem, false);
                if (!String.IsNullOrEmpty(validationMessage))
                    return gridModel.ContractorGrid.ShowEditValidationMessage(validationMessage);

                // Get the data from and find the item corresponding to the edited row
                Contractor item = (from x in datacontextModel.Contractors

SidBy.Sklad.Web/Views/Reference/Contractor.cshtml
@model SidBy.Sklad.Web.Models.SkladJqGridModel
@using SidBy.Sklad.Web.Models
@using Trirand.Web.Mvc

@Html.Partial("_JqGridStandart", new JqGridViewParamsModel() { 
    Grid = Model.ContractorGrid, GridId = "ContractorGrid1", Title = @ViewBag.Title})

<script type="text/javascript">
    function formatContactsLink(cellvalue, options, rowObject) {
       // console.log(rowObject);
        return '<ul class="grid-ui-icons"><li><a href="/MyCompany/ContactList?contractorId='
            + cellvalue + '" title="Контакты"><span class="ui-icon ui-icon-contact"></span></a></li> <li><a href="/MyCompany/ContractorDetails?contractorId='
        + cellvalue + '" title="Информация"><span class="ui-icon ui-icon-info"></span></a></li></ul>';
    }
    function unFormatContactsLink(cellvalue, options, cell) {
        return $('img', cell).attr('src');
    }
</script>

SidBy.Sklad.Web/Views/Reference/Product.cshtml
@model SidBy.Sklad.Web.Models.SkladJqGridModel
@using SidBy.Sklad.Web.Models
@using Trirand.Web.Mvc

@{
    string jqGridProductListId = "ProductList1";    
}

@Html.Trirand().JQAutoComplete(new JQAutoComplete { 
     AutoCompleteMode = AutoCompleteMode.BeginsWith,
        DataUrl = Url.Action("GetSupplierByCodeAutoComplete", "Reference"),
        DataField = "Code",
        ID = "ContractorId",
        //DataSource = (new SidBy.Sklad.DataAccess.SkladDataContext()).Contractors.Where(x => x.ContractorTypeId == 
        //    (int)SidBy.Sklad.Domain.Enums.EntityEnum.ContractorTypeEnum.Factory),
        DisplayMode = AutoCompleteDisplayMode.ControlEditor,
        MinLength = 2,  
}, "SupplierAutoComplete")

@Html.Trirand().JQGrid(Model.ProductGrid, jqGridProductListId)



@*// *@

<h2>Добавить новый товар</h2>
<label for="ContractorCode">Код фабрики</label>
<input type="text" id="ContractorCode" name="ContractorCode" />
<h3 class="SupplierName"></h3>
<input type="hidden" id="SupplierId" name="SupplierId" />
<div id="ProductFields" style="visibility:hidden;">
<fieldset>
    <legend>Создать товар</legend>
    <ol>
        <li>
            <label for="Article">Артикул</label>
            <input type="text" id="Article" name="Article" />
        </li>

        <li>
            <label for="PurchasePrice">Цена закупки</label>
            <input type="text" id="PurchasePrice" name="PurchasePrice" />
        </li>
        <li>
            <label for="SalePrice">Цена продажи</label>
            <input type="text" id="SalePrice" name="SalePrice" />
        </li>
        <li>
            <label for="VAT">НДС, %</label>
            <input type="text" id="VAT" name="VAT" />
        </li>
       
    </ol>
    <button id="AddNewProduct" name="AddNewProduct">Создать</button>
</fieldset>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#AddNewProduct").click(function () {
            if ($("#Article").val()) {
                if (!$("#PurchasePrice").val())
                    $("#PurchasePrice").val(0);
                if (!$("#SalePrice").val())
                    $("#SalePrice").val(0);
                if (!$("#VAT").val())
                    $("#VAT").val(0);

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("AddNewProduct", "Reference")",
                    success: function (data) {
                        jQuery("#@jqGridProductListId").trigger("reloadGrid");
                        $("#Article").val(''),
                        $("#PurchasePrice").val(''),
                        $("#SalePrice").val(''),
                        $("#VAT").val('')
                    },
                    data: {
                        "contractorId": $("#SupplierId").val(),
                        "article": $("#Article").val(),
                        "purchaseprice": $("#PurchasePrice").val(),
                        "saleprice": $("#SalePrice").val(),
                        "vat": $("#VAT").val()
                    }
                });
            }
        });

        $("#ContractorCode").autocomplete({
            source: function (request, response) {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("GetSupplierByCode", "Reference")",
                    data: { term: request.term, count: 20 },
                    contentType: "application/json;charset=utf-8",
                    dataType: "json",
                    processdata: true,
                    async: true,
                    cache: false,
                    success: function (data) {
                        response(data);
                    },
                })
            },
            minLength: 2,
            select: function (event, ui) {
                var text = "Добавить товар от фабрики: ";
                $(".SupplierName").text(text + ui.item.Name + " (" + ui.item.Code + ")");
                $("#SupplierId").val(ui.item.ContractorId);
                $("#ContractorCode").val(ui.item.Code);
                $("#ProductFields").css('visibility','visible').hide().fadeIn('slow');;
                return false;
            }
        }).data("ui-autocomplete")._renderItem = function (ul, item) {
            return $("<li>")
            .append("<a>" + item.Code + "</a>")
            .appendTo(ul);
            //"<br>" + item.Name + item.SurName + 
        };

    });
</script>

SidBy.Sklad.Web/Views/Reference/Region.cshtml
@model SidBy.Sklad.Web.Models.SkladJqGridModel
@using SidBy.Sklad.Web.Models
@using Trirand.Web.Mvc

@Html.Partial("_JqGridStandart", new JqGridViewParamsModel() { 
    Grid = Model.RegionGrid, GridId = "RegionGrid1", Title = @ViewBag.Title})